# Pendahuluan

## Latar Belakang {#sec-latar-belakang}

Secara global, penggunaan air yang berlebihan menyebabkan masalah lingkungan yang sangat serius dalam beberapa dekade terakhir [@vörösmarty2010]. Air yang dibutuhkan oleh manusia naik secara eksponensial semenjak masa pra-industrialisasi khususnya setelah tahun 1950-an [@riverine2018]. Krisis air yang terjadi bukan hanya terjadi dari sudut pandang manusia, namun juga biota air sungai yang hidup didalamnya. *World Wide Fund for Nature* atau @wwf2020, menyebutkan bahwa hingga 84% hewan air tawar di seluruh dunia telah berkurang sejak tahun 1970.

Di Indonesia sendiri, perubahan regim hidrologis akibat  kegiatan manusia seperti ekstraksi dan okupasi menyebabkan bertambahnya debit banjir dan berkurangnya debit andalan di Sungai Citarum Hulu [@nurcahyo2016]. Hal tersebut terjadi hampir bersamaan dengan rusaknya habitat ikan endemik yang ada [@istiqomah2021; @sunardi2012; @kartamihardja2019]. Kondisi tersebut menunjukkan bahwa Sungai Citarum Hulu dalam keadaan yang tidak baik karena keberagaman ikan merupakan salah satu indikator ekosistem sungai yang sehat [@leigh2012].

Dalam bidang hidrologi, mitigasi untuk krisis air dan habitat sungai diatas sebenarnya sudah diakomodasi dengan penentuan debit lingkungan (*environmental flow*). @acreman2004, mendefinisikan Debit lingkungan sebagai kuantitas atau volume air yang dibutuhkan dari waktu ke waktu untuk menjaga kesehatan sungai di suatu keadaan tertentu, di mana keadaan tersebut harus ditentukan sebelumnya atau disepakati berdasarkan *trade-off* dengan pertimbangan lain".

Terdapat 207 metode yang  bisa digunakan untuk menghitung debit lingkungan [@stamou2018]. Metode-metode tersebut kemudian bisa diklasifikasikan menjadi 4 (empat) bagian: hidrologi, hidraulik, habitat, dan holistik [@tharme2003]. Metode probabilitas Q~95~ [@sni6738:20152015]yang umumnya digunakan di Indonesia  masuk dalam klasifikasi metode hidrologi. Efektivitas penerapan metode Q~95~ ini masih perlu dikaji terutama terhadap respon balik habitat yang ada di sungai mengingat parameter yang dijadikan acuan hanya nilai debit tertentu.Hal ini sebenarnya bisa berbahaya karena konsekuensi perhitungan debit lingkungan yang sederhana bisa menimbulkan resiko kepada integritas masa depan dan  keanekaragaman hayati dari ekosistem sungai [@arthington2006]. Untuk itu perlu dilakukan kajian mengenai efektivitas metode yang umum digunakan beserta perbandingannya dengan metode lain dengan parameter yang lebih beragam serta kompleksitas yang lebih tinggi.

## Masalah Penelitian {#sec-masalah-penelitian}

Beberapa masalah penting yang akan dikaji pada penelitian ini adalah:

1.  Apa metode perhitungan debit lingkungan yang paling sesuai untuk digunakan di sungai Citarum hulu?

2.  Berapa nilai debit yang diperlukan untuk kelangsungan hidup ekosistem di sungai Citarum hulu?

3.  Seberapa besar *gap* atau selisih debit lingkungan terhadap debit eksisting?

4.  Upaya apa yang bisa digunakan untuk mencapai dan mempertahankan debit lingkungan tersebut?

## Maksud dan Tujuan Penelitian {#sec-maksud-dan-tujuan-penelitian}

Maksud dari penelitian ini adalah:

1.  Melakukan analisa kesenjangan (*gap*) debit.

2.  Mengidentifikasi kondisi habitat di sungai Citarum hulu.

3.  Mengkaji Metode debit lingkungan yang paling tepat digunakan di sungai Citarum hulu.

Sedangkan Tujuan yang ingin diperoleh pada penelitian ini adalah:

1.  Memperoleh nilai debit lingkungan yang mengakomodir kondisi hidrologi, peraturan/undang-undang yang ada, serta kebutuhan ekosistem habitat.

2.  Mendapatkan nilai gap debit lingkungan terhadap debit sekarang.

3.  Memperoleh metode yang paling tepat untuk menentukan parameter debit lingkungan yang sesuai dengan kondisi lapangan

## Lingkup Studi {#sec-lingkup-studi}

## Batasan Masalah {#sec-batasan-masalah}

## Lokasi Kajian {#sec-lokasi-kajian}

## Sistematika Penulisan {#sec-sistematika-penulisan}
