---
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: "**Irpan Chumaedi**"
title: "Kajian Debit Lingkungan di Sungai Citarum Hulu"
#subtitle: "`r params$client_company`, `r params$kecamatan`, `r params$kabupaten`"
output:
  #bookdown::html_document2: default
  bookdown::word_document2: 
    #reference_docx: template_thesis.docx
  #officedown::rdocx_document:
    #reference_docx: template.docx
params:
  river_location: "Citarum"
  name_ca: "Citarum"
  length_river: 550
  length_river_proyek: 550
  slope_river: 0.002
  slope_river_proyek: 0.0003
  area_ca: 11542
  kecamatan: "Babakan Cikao"
  kabupaten: "Purwakarta"
  provinsi: "Jawa Barat"
  sta_hujan1: "Sta. Hujan Cikao"
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  # Table captioning
  tab.cap.style = "Table Caption",
  tab.cap.pre = "Table ",
  tab.cap.sep=": ",
  # Figure captioning
  fig.cap.style = "Image Caption",
  fig.cap.pre = "Figure ",
  fig.cap.sep=": ",
  fig.align = "center",
  fig.width = 6,
  dpi=600
)

# Libraries
library(officedown)
library(officer)
library(tidyverse)
library(timetk)
library(dplyr)
library(lubridate)

# Import data
# rainfall_data <- read_csv("01_data/rainfall_data.csv")
# rainfall_data <- rainfall_data %>% 
  # filter(rainfall_mm != "-") %>% #hilangkan data yang kosong
  # mutate(date=mdy(date)) #ganti tipe kolom menjadi tanggal

```

\newpage

# Abstrak {.unnumbered}

\newpage

# Abstract {.unnumbered}

\newpage

# Halaman Pengesahan {.unnumbered}

\newpage

# Daftar Isi {.unnumbered}

\newpage

# Daftar Gambar {.unnumbered}

\newpage

# Daftar Tabel {.unnumbered}

\newpage

# Pendahuluan

## Latar Belakang

Secara global, penggunaan air yang berlebihan menyebabkan masalah lingkungan yang sangat serius dalam beberapa dekade terakhir [@vörösmarty2010]. Air yang dibutuhkan oleh manusia naik secara eksponensial semenjak masa pra-industrialisasi khususnya setelah tahun 1950-an [@riverine2018]. Krisis air yang terjadi bukan hanya terjadi dari sudut pandang manusia, namun juga biota air sungai yang hidup didalamnya. *World Wide Fund for Nature* atau @wwf2020 , menyebutkan bahwa hingga 84% hewan air tawar di seluruh dunia telah berkurang sejak tahun 1970.

Di Indonesia sendiri, perubahan regim hidrologis akibat  kegiatan manusia seperti ekstraksi dan okupasi menyebabkan bertambahnya debit banjir dan berkurangnya debit andalan di Sungai Citarum Hulu [@nurcahyo2016]. Hal tersebut terjadi hampir bersamaan dengan rusaknya habitat ikan endemik yang ada [@istiqomah2021; @kaniawati2012; @kartamihardja2019]. Kondisi tersebut menunjukkan bahwa Sungai Citarum Hulu dalam keadaan yang tidak baik karena keberagaman ikan merupakan salah satu indikator ekosistem sungai yang sehat [@leigh2012].

Dalam bidang hidrologi, mitigasi untuk krisis air dan habitat sungai diatas sebenarnya sudah diakomodasi dengan penentuan debit lingkungan (*environmental flow*). @acreman2004, mendefinisikan Debit lingkungan sebagai kuantitas atau volume air yang dibutuhkan dari waktu ke waktu untuk menjaga kesehatan sungai di suatu keadaan tertentu, di mana keadaan tersebut harus ditentukan sebelumnya atau disepakati berdasarkan *trade-off* dengan pertimbangan lain".

Terdapat 207 metode yang  bisa digunakan untuk menghitung debit lingkungan [@stamou2018]. Metode-metode tersebut kemudian bisa diklasifikasikan menjadi 4 (empat) bagian: hidrologi, hidraulik, habitat, dan holistik [@tharme2003]. Metode probabilitas Q~95~ [@sni6738:20152015] yang umumnya digunakan di Indonesia  masuk dalam klasifikasi metode hidrologi. Efektivitas penerapan metode Q~95~ ini masih perlu dikaji terutama terhadap respon balik habitat yang ada di sungai mengingat parameter yang dijadikan acuan hanya nilai debit tertentu.Hal ini sebenarnya bisa berbahaya karena konsekuensi perhitungan debit lingkungan yang sederhana bisa menimbulkan resiko kepada integritas masa depan dan  keanekaragaman hayati dari ekosistem sungai [@arthington2006]. Untuk itu perlu dilakukan kajian mengenai efektivitas metode yang umum digunakan beserta perbandingannya dengan metode lain dengan parameter yang lebih beragam serta kompleksitas yang lebih tinggi.

## Masalah Penelitian

## Maksud dan Tujuan Penelitian

## Lingkup Studi

## Batasan Masalah

## Lokasi Kajian

## Sistimatika Penulisan

# Tinjauan Pustaka

## Studi Literatur

### Kerangka Pikir (*Framework*)

### Metode dan Aplikasi (*Method and practice*)

### Kondisi Sungai Citarum Hulu (*Overview Upper Citarum*)

### Studi Kasus mengenai habitat (*Habitual Study Cases*)

### Studi Kasus Mengenai hidrologi (*Hidrological Study Cases*)

## Sungai dan DAS

## Analisa Debit Lingkungan

### Metode Hidrologi

### Metode Hidrolika

### Metode Simulasi Habitat

### Metode Holistik

# Metodologi Penelitian

# Analisa Sementara

## Analisa Lengkung Durasi Debit (*Flow Duration Curve Analysis*)

## Analisa Kesenjangan Debit (*Gap Analysis*)

## Tinjauan Berdasarkan Aturan Lingkungan

## Analisa Kecocokan Habitat (*Habitat Suitability*)

# Kesimpulan Sementara

# Daftar Pustaka
